spring.application.name=crud_api
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/crud_api
spring.jpa.hibernate.ddl-auto=update